// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VGenerate_Sensor_Trips.cpp"
#include "VGenerate_Sensor_Trips__Slow.cpp"
#include "VGenerate_Sensor_Trips__Syms.cpp"
