.PHONY: all validate

all: validate

validate:
	lando validate RTS.lando
	lando validate dataflow.lando
	lando validate instrumentation.lando
	lando validate acronyms.lando
	lando validate glossary.lando
	lando validate project_requirements.lando
	lando validate architecture.lando
	lando validate hardware.lando
	lando validate tool_scenarios.lando
